package com.gradlemedium100.security.model;

/**
 * Enumeration of user roles within the system for authorization purposes.
 * Follows Spring Security naming conventions where authorities are prefixed with "ROLE_".
 * 
 * This enum provides the standard roles used for access control throughout the application,
 * implementing a hierarchical permission structure with increasing privileges.
 */
public enum Role {
    /**
     * User role with basic permissions for general authenticated users.
     */
    USER,
    
    /**
     * Customer service role with permissions to handle user support tasks.
     */
    CUSTOMER_SERVICE,
    
    /**
     * Manager role with elevated permissions for department-level operations.
     */
    MANAGER,
    
    /**
     * Administrator role with system configuration and management permissions.
     */
    ADMIN;

    /**
     * Returns the authority representation of this role, prefixed with ROLE_ as required
     * by Spring Security's default role-based authorization.
     * 
     * @return String representation of the role authority (e.g., "ROLE_USER")
     */
    public String getAuthority() {
        // Return the role name prefixed with ROLE_ as per Spring Security convention
        return "ROLE_" + this.name();
    }
    
    // Inherited methods from Enum:
    
    /**
     * Returns an array containing the constants of this enum type, in the order they are declared.
     * 
     * @return an array containing the constants of this enum type, in the order they are declared
     */
    // public static Role[] values();
    
    /**
     * Returns the enum constant of this type with the specified name.
     * The string must match exactly an identifier used to declare an enum constant in this type.
     *
     * @param name the name of the constant to return
     * @return the enum constant with the specified name
     * @throws IllegalArgumentException if this enum type has no constant with the specified name
     * @throws NullPointerException if the argument is null
     */
    // public static Role valueOf(String name);
    
    // Note: values() and valueOf(String) methods are automatically 
    // generated by the Java compiler for all enum types
}